### ISSUE TITLE
[FEATURE] add button stop/disable

### ISSUE THREAD

**Issue by Aliaksandr3by** [ahmoylaw/RegexTrainer-Descriptions#11]
If I handle many words (f.e. 30 000) the Trainer will go to suspend.
I would like to have buttons to timely disable or stopped working.

![image](https://user-images.githubusercontent.com/11432724/161412776-cca42a91-298a-49e0-b57d-33e35c4e61a1.png)

**Comment by ahmoylaw** [comment]
This simple plugin will not able to handle this logic as it will just find all matches and hilight matches in one shot.
Maybe will implement a better logic in the future version.
