### ISSUE TITLE
Dollar sign

### ISSUE THREAD

**Issue by anankee26** [ahmoylaw/RegexTrainer-Descriptions#12]
Hello,

Is there a bug with dollar sign ? When I test this:
```
zzz.example.check
zzz.example
zzz.newexam
```
With regex 
`zzz\.(\w)*$`
, nothing display. If I remove the $, all lines are matches.
In options, just "global find" is check.

With notepad++ and its find's popup, I find
```
	Ligne 2: zzz.example
	Ligne 3: zzz.newexam
```
In fact, what i want to find.
Same result if I try with https://www.regextester.com for instance.

So, why is there no result with "regextrainer" ?
thx

**Comment by ahmoylaw** [comment]
Sorry, RegexTrainer is just a wrapper to the .Net regex library...  I really can't help much on why the regex result is different from others.  There is a possibility that the first line and second line end with \r and not \n as expected for $, and as a result only the last line will be hilighted.
