### ISSUE TITLE
Regex panel icon doesn't work

### ISSUE THREAD

**Issue by KnewOne** [ahmoylaw/RegexTrainer-Descriptions#13]
Pressing on icon launches graphics for it being pressed but the panel doesn't appear. It does appear if pressed in the drop-down menu. 
![image](https://user-images.githubusercontent.com/41551327/175426472-fb2af8f4-bcb1-4c47-8dad-487eba798092.png)

Plugins installed:
![image](https://user-images.githubusercontent.com/41551327/175426575-8d151a65-0069-4ba1-b40f-0fa8e04411b0.png)
Net Framework 4.8
Win 10, NP++ v8.4.2

**Comment by Fruchtzwerg94** [comment]
Exactly the same for me.

**Comment by wonkawilly** [comment]
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/34818345/d3342846-f588-4417-b20c-ac594916ec8a)

RegexTrainer icon on Notepad++ toolbar doesn't work for me either: when I click it, nothing happens.
I used the plugin in multiple N++ versions and now I am using the latest one (8.5.3 32bit) and in no version that icon has ever worked.
I suppose this interesting plugin needs a little fine tuning to solve the little issue for future RegexTrainer versions releases... as soon as possible I hope.
Thanks you.

**Comment by ahmoylaw** [comment]
Icon on the toolbar will be removed under ver 1.1.0
sorry for no noticing the icon...
