### ISSUE TITLE
Save expression

### ISSUE THREAD

**Issue by bryandaugherty-pki** [ahmoylaw/RegexTrainer-Descriptions#14]
I have a feature request: It would be nice to be able to save the expression so that it's not lost when closing the panel or Notepad++. It would be even better if I could save expressions and name them so they could appear in a list maybe between the "Matches" section and the "Quick Reference" section. This would allow me to quickly reload past expressions from a library.

This is a great plugin! Thanks for making it.

**Comment by wonkawilly** [comment]
I suppose that should be great to have an History like menu where users can save typed expression under a name. And these will be saved into a history.xml file in the same directory of the main dll so can be even transferred or shared from computers and even online with ease.

**Comment by ahmoylaw** [comment]
Will be available under ver 1.1.0
It will be saved into RegexTrainer.ini inside the default plugin folder for notepad++.
