### ISSUE TITLE
clear all marks and stop analyzing

### ISSUE THREAD

**Issue by Aliaksandr3by** [ahmoylaw/RegexTrainer-Descriptions#17]
clear all marks and stop analyzing

![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/9a390a00-fe62-4ea5-afde-b68af178d4d6)

**Comment by ahmoylaw** [comment]
The logic for current version will only return complete matches and then highlight the matches.
What the "Mark All", "Clear all marks" and "Disable/Enable analyze" buttons are used for?

**Comment by ahmoylaw** [comment]
btw, i dont think we can get a new Notepad++ with the new RegexTrainer ver1.1.0 yet... how do you even test it out already?

**Comment by ahmoylaw** [comment]
After staring at your modified screenshot, can i say that the buttons are for the tasks below?

1. "Clear all marks" - will clear the hilights (although there are matches found and displayed the Matches' list)
2.  "Mark all" - will apply the hilights again (since the "Clear all marks" has removed the hilights)
3. "Disable analyze" - will temporary stop processing on what user has entered inside the Expression's textbox.  "Enable analyze" will continue finding the maches on what has user entered inside the Expression's textbox.  Currently the finding process will be triggered in every 2 seconds if there is a changes inside the textbox. so, the "Enable/Disable analyze" button will disable the automation 2 seconds timer and will operate manually.

**Comment by Aliaksandr3by** [comment]
I am using 

![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/90d80a5a-1d13-40fb-9886-b4bc249e0ad2)

![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/18eeffd3-741b-41be-9b5b-25457fc21998)

**Comment by Aliaksandr3by** [comment]
I sometimes extract some data with regex. for that reason I use integrated features the N++.
And I have the problem if regTrainer highlights text, npp do the same .

![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/f5b97205-2147-4e23-be55-cd2d779a633a)

**Comment by Aliaksandr3by** [comment]
I will be very appreciated if you will make the button "clear all marks" for clear all highlighters,
Now I use simple deleting the text for de-highlighter.

![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/0da08be5-eb27-4a43-9f02-643f558b906b)

**Comment by ahmoylaw** [comment]
Ok, i will update RegexTrainer again in coming few days. Need to tweak it a bit to add clear or re highlight markers again.

**Comment by ahmoylaw** [comment]
Added Mark All, Clear All Marks and Copy Marked Text To Clipboard for version 1.2.0.

**Comment by Aliaksandr3by** [comment]
how to start use it?
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/3fac4793-5f03-4310-89ed-c3ac1e578046)
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/59f869d3-a95d-4671-a9e9-5f4d33b16883)

**Comment by ahmoylaw** [comment]
What happened to that 3 buttons??? Can you try to resize panel to force it to repaint …

**Comment by Aliaksandr3by** [comment]
I did trying it, nope

**Comment by Aliaksandr3by** [comment]
and it will crash
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/7eb5a003-3d31-4b2e-b5aa-3be2c92768e6)

**Comment by ahmoylaw** [comment]
and not responding some more... facepalm!!!
Can you try to restart your notepad++?

**Comment by Aliaksandr3by** [comment]
I use portatible version of npp
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/e45f3ddf-401a-4f63-8d4e-946d38a71328)


OS Name	Microsoft Windows 11 Pro
 64 Version	10.0.22000 Build 22000

**Comment by ahmoylaw** [comment]
![screenshot](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/64273309/488e432f-34fd-4ca9-9970-743a414fe9b9)

it should display buttons something like this...

**Comment by Aliaksandr3by** [comment]
may be do you not recompile the 64b version?

**Comment by ahmoylaw** [comment]
Can you try to uninstall the plugin and reinstall it again?

**Comment by Aliaksandr3by** [comment]
i copy to the file to .\npp.portable.x64\plugins\RegexTrainer\RegexTrainer.dll many times, it is don't work.

can you try to test it with this version? 
Portable (zip) | GPG Signature
https://notepad-plus-plus.org/downloads/v8.5.7/

**Comment by Aliaksandr3by** [comment]
new clean install does't work also
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/eb653967-68f4-42f4-bc7d-a5711e1af16f)

**Comment by ahmoylaw** [comment]
Strange...  i installed notepad++ portable ver 8.5.7 and i could only see RegexTrainer ver 1.0.0

**Comment by Aliaksandr3by** [comment]
sorry, I don't know how it is work, but yah
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/5d5884b3-c1a7-44f6-ad7e-c14dc40fc584)

https://github.com/notepad-plus-plus/nppPluginList/blob/master/doc/plugin_list_x64.md

**Comment by ahmoylaw** [comment]
Can you manually download the binary from this link and replace the installed plugin?

https://github.com/ahmoylaw/RegexTrainer-Descriptions/raw/master/Release-x64-1.2.0/RegexTrainer.zip

You need to extract it first...

**Comment by ahmoylaw** [comment]
Btw, what is the .Net version installed inside your machine?  For Regex 1.2.0, the .net version set is 4.8.

**Comment by Aliaksandr3by** [comment]
PowerShell 7.3.7
PS C:\Users\shpak> dotnet --list-sdks
3.1.426 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
PS C:\Users\shpak> dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by ahmoylaw** [comment]
emmm... you machine has three versions of .net, 3.1.32, 6.0.5 and 6.0.22... 

My machine only reports this...
Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by ahmoylaw** [comment]
Can you revert the RegexTrainer back to ver 1.1.0?
Get the binary from here...
https://github.com/ahmoylaw/RegexTrainer-Descriptions/raw/master/Release-x64-1.1.0/RegexTrainer.zip

**Comment by Aliaksandr3by** [comment]
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/a9036597-1540-419c-b08b-559b856da2c7)

**Comment by ahmoylaw** [comment]
so, you can run the version 1.1.0 without any error?

**Comment by Aliaksandr3by** [comment]
yes

**Comment by Aliaksandr3by** [comment]
but 1.2 go to waiting
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/7b8367dc-1904-4549-9a97-3c1403ab6c21)

![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/072f2b48-f36a-4e05-a4e0-bf5b545b4d4a)

**Comment by ahmoylaw** [comment]
Can you test using a new binary 64-bit from this link?
https://github.com/ahmoylaw/RegexTrainer-Descriptions/raw/master/Release-x64-1.2.1/RegexTrainer.zip

**Comment by Aliaksandr3by** [comment]
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/552d0c62-c5f8-4a9a-8b3f-fb69254dc261)
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/a432ccf3-fe6c-46eb-86ff-eb693f204739)

**Comment by Aliaksandr3by** [comment]
There will be no bug correction?

**Comment by ahmoylaw** [comment]
Hi Aliaksandr,I will start looking on RegexTrainer again next week. Been very busy with my current project.From,Ahmoy LawOn Oct 2, 2023, at 11:43 PM, Aliaksandr ***@***.***> wrote:﻿
There will be no bug correction?

**Comment by ahmoylaw** [comment]
Hi, can you try with this test binary?  

https://github.com/ahmoylaw/RegexTrainer-Descriptions/raw/master/Test/RegexTrainer_Test_1.zip

This binary will disable some of functionatility for Matches output's UI.  I suspect that the custom ListView for the Matches gives problem to your machine (which weirdly doesnt give issue to my machine).  Please help me to test this binary and reply me whether the RegexTrainer is still hang or not.

**Comment by Aliaksandr3by** [comment]
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/be13cb89-7bb2-4e59-b1c9-69ef1b53001b)

**Comment by ahmoylaw** [comment]
Can you put more description to your finding?  Before showing the Options form, the test binary does not hang?

**Comment by Aliaksandr3by** [comment]
it is clear, I only move main window of regextrainer

**Comment by Aliaksandr3by** [comment]
the Trainer is working
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/dc06bf9d-652b-489b-8cb6-345a793e5f89)

**Comment by Aliaksandr3by** [comment]
video
[2023-10-10 08-50-27.zip](https://github.com/ahmoylaw/RegexTrainer-Descriptions/files/12853276/2023-10-10.08-50-27.zip)

**Comment by ahmoylaw** [comment]
Oh!  The moving around the plugin written with c# (.net) will sometimes give us a not responsive screen since NPP is native and RegexTrainer is in .net and this .net plugin is not that stable (well known issue, even happened on my machine).  Cant do much about that though...

So, the main culprit for your machine is the custom listview!

**Comment by Aliaksandr3by** [comment]
ok. it is no problem.

sorry. I don't understand what is problem?
on clean n++ the same error
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/64a82241-e7c7-4744-a3bd-776aa20a3023)

**Comment by Aliaksandr3by** [comment]
new button is don't exist
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/8b464ded-92e1-49b3-bae5-77ac7913e7c2)

**Comment by ahmoylaw** [comment]
Can you try with the Test 2 binary?

https://github.com/ahmoylaw/RegexTrainer-Descriptions/raw/master/Test/RegexTrainer_Test_2.zip

Please check whether the new buttons are available or not.

**Comment by Aliaksandr3by** [comment]
nop
I have win11-64_pro with last update
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/326793d3-664f-472b-becc-c4dd3407b540)

**Comment by Aliaksandr3by** [comment]
info: plugin don't work on windows 7_64

**Comment by ahmoylaw** [comment]
1. can you resize the regex trainer plugin to force repaint?
2. is the Options button responsive?  Click and it will show the Options screen?
3. is the Save Regex button responsive?

**Comment by Aliaksandr3by** [comment]
1. did it many time
2. yes
3. yes

![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/06c7222b-f465-46d2-8d14-5e46cd99d661)

[2023-10-10 11-08-18.zip](https://github.com/ahmoylaw/RegexTrainer-Descriptions/files/12854432/2023-10-10.11-08-18.zip)

**Comment by Aliaksandr3by** [comment]
the RegexTrainer is very good program, I use it every time. thx, but I think that finding out the error is take too much time.
may by the best options is rollback.
thx for you's work

**Comment by ahmoylaw** [comment]
Can you try with the last Test 3 binary? I moved the button to difference places.

https://github.com/ahmoylaw/RegexTrainer-Descriptions/raw/master/Test/RegexTrainer_Test_3.zip

**Comment by ahmoylaw** [comment]
Oppssss... do not doqnload first!

**Comment by ahmoylaw** [comment]
Ok, can you try the latest test binary?

https://github.com/ahmoylaw/RegexTrainer-Descriptions/raw/master/Test/RegexTrainer_Test_3.zip

**Comment by Aliaksandr3by** [comment]
thx, nice work (i will test more)
may be good idea to add options 'transpond" when do I copy in clipboard?
![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/11ff1190-e40a-4d43-b42e-4d4c2330e605)

**Comment by ahmoylaw** [comment]
Can you explain more on transpond?

**Comment by Aliaksandr3by** [comment]
> Can you explain more on transpond?

sorry, my english is bad.
**transpose**

![image](https://github.com/ahmoylaw/RegexTrainer-Descriptions/assets/11432724/5bc80b87-e627-46e4-b8c7-1eb598421e22)

**Comment by ahmoylaw** [comment]
So, instead of a new line between the copied items, it should use a tab character?  doubt that this feature will be used by others...  let me think on how to integrate this into the current feature if possible.

**Comment by Aliaksandr3by** [comment]
maybe.
I think "\r?\n" is good work enough
