### ISSUE TITLE
does not work with cyrillic (belarus lang)

### ISSUE THREAD

**Issue by Aliaksandr3by** [ahmoylaw/RegexTrainer-Descriptions#2]
does not work with Cyrillic (Belarus lang)

[new 2.txt](https://github.com/ahmoylaw/RegexTrainer-Descriptions/files/5394827/new.2.txt)

![image](https://user-images.githubusercontent.com/11432724/96325431-3cd50480-1030-11eb-958b-727f2c9d80ec.png)

**Comment by ahmoylaw** [comment]
Hi, 

Can you check whether the found locations is correct or not? Maybe there is a bug when extracting character from the found location to display inside result.

From,
Law

**Comment by Aliaksandr3by** [comment]
![image](https://user-images.githubusercontent.com/11432724/96338259-62e0c000-1095-11eb-880f-446ce149eec4.png)
![image](https://user-images.githubusercontent.com/11432724/96338263-683e0a80-1095-11eb-8d3a-008e7da4b7c4.png)
![image](https://user-images.githubusercontent.com/11432724/96338276-7ab84400-1095-11eb-8dc3-f7aa896411ba.png)
![image](https://user-images.githubusercontent.com/11432724/96338278-7db33480-1095-11eb-820b-27d926d4ea74.png)
