### ISSUE TITLE
RegexTrainer panel does NOT display

### ISSUE THREAD

**Issue by David-Maisonave** [ahmoylaw/RegexTrainer-Descriptions#4]
When selecting the [Show Panel] option, the panel (window) does not display.  Nothing happens.
The same results occur when pressing the tool bar [.*] option.

I can not get the plugin to work at all.
I have the latest version of Notepad++ (v7.9.1) 64-bit installed on Windows 10 Pro.
I've tried installing this plugin from the Plugin Manager and I also tried downloading the version from here (GitHub), but I get the same results.

Can the source code be made available, so that others can try making fixes or help with enhancements?

I created a similar regex help feature for a logging program, and I would like to help on this project.

**Comment by ahmoylaw** [comment]
Hi David,

Does your computer come with .net library? And what is version .net installed?

From,
Law

**Comment by ahmoylaw** [comment]
Any lucks so far for solving your issue?

From,
Law

**Comment by David-Maisonave** [comment]
I just tried the latest version of Notepad++ (v8.5.3) with the latest version of RegexTrainer, and it's now working for me.
Thank you
