### ISSUE TITLE
does the \Q....\E sequence not support?

### ISSUE THREAD

**Issue by Aliaksandr3by** [ahmoylaw/RegexTrainer-Descriptions#8]
does the \Q....\E sequence not support?

![image](https://user-images.githubusercontent.com/11432724/105943385-3401bf00-6072-11eb-9799-c34e363a9165.png)

**Comment by ahmoylaw** [comment]
Hi Aliaksandr,

If I remember it correctly, .net regular expression does not support it. You can check it from the description list.

From,
Law

**Comment by wonkawilly** [comment]
Same problem with **\R** it is not recognized either.
