### ISSUE TITLE
there is no code only the binaries. disapointed

### ISSUE THREAD

**Issue by grandSebMoodys** [ahmoylaw/RegexTrainer-Descriptions#9]
hi i'm disapointed, i thought to find the sources of your plugin as good example hot to start a plugin but i was surprised to found that there is only zip of the compiled dll.
too bad

**Comment by ownwolf** [comment]
小可爱，源码呢

**Comment by ahmoylaw** [comment]
RegexTrainer is just a very simple plugin (written in c#), nothing special about the code.
You can start developing a new plugin by downloading the c# plugin for notepad++from here... https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net
